name: 'Terraform'

on:
  push:
    branches: [ 'main' ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform Deployment'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    environment:
      name: prd

    env:
      AWS_REGION: us-east-1
      ENV_DIR: prd
      TF_VAR_confluent_cloud_api_key: ${{ secrets.TF_VAR_CONFLUENT_CLOUD_API_KEY }}
      TF_VAR_confluent_cloud_api_secret: ${{ secrets.TF_VAR_CONFLUENT_CLOUD_API_SECRET }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Format Check
      run: make fmt-check

    - name: Terraform Init
      run: make init

    - name: Terraform Plan
      run: make plan

    - name: Terraform Apply
      run: make apply
